Using CSV

In [3]:
import csv
with open ('/home/AIML_Student/Documents/33B/pl.csv','rt') as f:
    data=csv.reader(f)
    for row in data:
        print(row)
        

['Programming Language', ' Designed By', ' Appeared', ' Extension']
['python', 'Guido Van Rossum', '1991', '.py']
['java', 'James Gosling', ' 1995', '.java']
['c++', 'Bjarne Stroustrup', '1983', '.cpp']


In [6]:
import csv
reader=csv.DictReader(open('/home/AIML_Student/Documents/33B/pl.csv','rt'))
for raw in reader:
        print(raw)
        

{'Programming Language': 'python', ' Designed By': 'Guido Van Rossum', ' Appeared': '1991', ' Extension': '.py'}
{'Programming Language': 'java', ' Designed By': 'James Gosling', ' Appeared': ' 1995', ' Extension': '.java'}
{'Programming Language': 'c++', ' Designed By': 'Bjarne Stroustrup', ' Appeared': '1983', ' Extension': '.cpp'}


In [25]:
import csv
with open ('/home/AIML_Student/Documents/33B/pl1.csv','w') as f:
    writer=csv.writer(f,delimiter=',',quotechar='"',quoting=csv.QUOTE_MINIMAL)
    writer.writerow(['Programming Language', ' Designed By', ' Appeared', ' Extension'])
    writer.writerow(['python', 'Guido Van Rossum', '1991', '.py'])
    writer.writerow(['java', 'James Gosling', ' 1995', '.java'])
    writer.writerow(['c++', 'Bjarne Stroustrup', '1983', '.cpp'])
with open ('/home/AIML_Student/Documents/33B/pl1.csv','rt') as f:
    data=csv.reader(f)
    for row in data:
        print(row)

['Programming Language', ' Designed By', ' Appeared', ' Extension']
['python', 'Guido Van Rossum', '1991', '.py']
['java', 'James Gosling', ' 1995', '.java']
['c++', 'Bjarne Stroustrup', '1983', '.cpp']


using Dataframe

In [2]:
from pandas import DataFrame
c={'Programming Language':['Python','Java','C++'],
  ' Designed By':['Guido Van Rossum','James Gosling','Bjarne Stroustrup'],
   ' Appeared':['1991','1995','1983'],
   ' Extension':['.py','.java','.cpp']
  }
df=DataFrame(c,columns=['Programming Language', ' Designed By', ' Appeared', ' Extension'])
export_csv=df.to_csv(r'/home/AIML_Student/Documents/33B/pl2.csv',index=None,header=True)
print(df)

  Programming Language        Designed By  Appeared  Extension
0               Python   Guido Van Rossum      1991        .py
1                 Java      James Gosling      1995      .java
2                  C++  Bjarne Stroustrup      1983       .cpp


*!pip install numpy

1. Convert a 1-D array into a 2-D array with 3 rows.

In [43]:
import numpy as np
a=np.array([0,1,2,3,4,5,6,7,8])
print('initial array: ',a)
b=a.reshape(3,3)
print('Modified array:')
print(b)

initial array:  [0 1 2 3 4 5 6 7 8]
Modified array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


2. Replace all odd numbers in the given array with -1

In [47]:
a=np.array([0,1,2,3,4,5,6,7,8])
print('initial array: ',a)
n=a.size
for i in range(n):
    if a[i]%2!=0:
        a[i]=-1
print('Modified Array',a)

initial array:  [0 1 2 3 4 5 6 7 8]
Modified Array [ 0 -1  2 -1  4 -1  6 -1  8]


3. Find the positions of:
elements in x where its value is more than its corresponding element in y, and elements in x where its value is equals to its corresponding element in y.

In [56]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
m=[]
n=[]
for i in range(y.size):
    if x[i]==y[i]:
        m.append(i)
    if x[i]>y[i]:
        n.append(i)
print('X is equals to Y at: ',m)
print('X is grater than Y at: ',n)

X is equals to Y at:  [0]
X is grater than Y at:  [1, 2, 4, 5, 6, 7, 8, 9]


4. Extract the first four columns of this 2-D array.

In [64]:
a= np.arange(100).reshape(5,-1)
print(a)
b=a[:,[0,1,2,3]]
print(b)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]
[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]
